version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./data:/app/data
    depends_on:
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:13
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cuicui-db
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=53Cre7*@

  redis:
    image: redis:6
    volumes:
      - ./redis-data:/data
